apiVersion: apps/v1
kind: Deployment
metadata:
  name: mmrr
  labels:
    app: mmrr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mmrr
  template:
    metadata:
      labels:
        app: mmrr
    spec:
      #      restartPolicy: OnFailure
      imagePullSecrets:
        - name: fly-reg
      containers:
        - name: rabbitmq
          image: fly.reg.com/rabbitmq:3.9.11
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 15672
            - containerPort: 5672
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: flyos
            - name: RABBITMQ_DEFAULT_PASS
              value: "123456"
          volumeMounts:
            - name: time
              mountPath: /etc/localtime
              readOnly: true
        - name: redisjson
          image: fly.reg.com/redisjson:2.0.6
          imagePullPolicy: IfNotPresent
          command:
            - redis-server
            - --port 6380
            - --loadmodule /usr/lib/redis/modules/rejson.so
            - --loadmodule /usr/lib/redis/modules/redisearch.so
          ports:
            - containerPort: 6380
          volumeMounts:
            - name: time
              mountPath: /etc/localtime
              readOnly: true
        - name: redis
          image: fly.reg.com/redis:6.2.6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: time
              mountPath: /etc/localtime
              readOnly: true
        - name: mysql
          image: fly.reg.com/mysql:5.7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: toor
          volumeMounts:
            - name: time
              mountPath: /etc/localtime
              readOnly: true
      volumes:
        - name: time
          hostPath:
            path: /etc/localtime
---
apiVersion: v1
kind: Service
metadata:
  name: mmrr
spec:
  type: NodePort
  selector:
    app: mmrr
  ports:
    - name: mq-mgr
      port: 15672
      targetPort: 15672
      nodePort: 31001
    - name: mq
      port: 5672
      targetPort: 5672
      nodePort: 30001
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30002
    - name: redis
      port: 6379
      targetPort: 6379
      nodePort: 30003
    - name: redisjson
      port: 6380
      targetPort: 6380
      nodePort: 30004