apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      imagePullSecrets:
        - name: fly-reg
      containers:
        - name: redis
          image: fly.reg.com/redis:6.2.6
          imagePullPolicy: IfNotPresent
          command: # 启动配置端口 参考 redis 的 Dockerfile CMD ["redis-server"]
            - redis-server
            - --port 6379
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis
              mountPath: /etc/localtime
              readOnly: true
      volumes:
        - name: redis
          hostPath:
            path: /etc/localtime
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: NodePort
  selector:
    app: redis
  ports:
    - name: http
      port: 6379
      targetPort: 6379
      nodePort: 30003