apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisjson
  labels:
    app: redisjson
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redisjson
  template:
    metadata:
      labels:
        app: redisjson
    spec:
      imagePullSecrets:
        - name: fly-reg
      containers:
        - name: redisjson
          image: fly.reg.com/redisjson:2.0.6
          imagePullPolicy: IfNotPresent
          command: # 启动配置端口 参考源码中的 Dockerfile https://github.com/RedisJSON/RedisJSON/blob/master/Dockerfile
            - redis-server
            - --port 6379 # 指定端口
            - --loadmodule /usr/lib/redis/modules/rejson.so
            - --loadmodule /usr/lib/redis/modules/redisearch.so
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redisjson
              mountPath: /etc/localtime
              readOnly: true
      volumes:
        - name: redisjson
          hostPath:
            path: /etc/localtime
---
apiVersion: v1
kind: Service
metadata:
  name: redisjson
spec:
  type: NodePort
  selector:
    app: redisjson
  ports:
    - name: http
      port: 6379
      targetPort: 6379
      nodePort: 30004