# eureka配置，
HOSTNAME: blackbox # 本服务实例域名
PORT: 8763 # 本服务实例端口
GZ_IP: 127.0.0.1 # eureka 注册中心ip
GZ_PORT: 8761 # eureka 注册中心端口
SZ_IP: 127.0.0.1 # eureka 注册中心ip
SZ_PORT: 8762 # eureka 注册中心端口
REGISTER-WITH-EUREKA: false #实例是否在eureka服务器上注册自己的信息以供其他服务发现，默认为true 注册中心可设为false
FETCH_REGISTRY: false #实例是否在eureka服务器上注册自己的信息以供其他服务发现，默认为true 注册中心可设为false
# 管理接口 配置
MPATH: /admin # management.endpoints.web.base-path
VERSION: 0.0.1 # 本服务版本号
APPDESC: 注册中心 # 本服务描述信息

# 日志
LOGLEV: WARN
# enc() 加密配置文件
KEY: bougainvillea