/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.bougainvilleas.ilj.app;

import org.apache.commons.text.WordUtils;
import org.bougainvilleas.ilj.list.LinkedList;

import static org.bougainvilleas.ilj.app.MessageUtils.getMessage;
import static org.bougainvilleas.ilj.utilities.StringUtils.join;
import static org.bougainvilleas.ilj.utilities.StringUtils.split;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
