# 管理接口 配置
MPATH: /admin # management.endpoints.web.base-path
VERSION: 0.0.3 # 本服务版本号
APPDESC: 配置中心客户端 # 本服务描述信息
# 日志
LOGLEV: INFO
# enc() 加密配置文件
KEY: bougainvillea

swagger:
  enable: true
  info:
    title: ${spring.application.name}
    description: ${APPDESC}
    version: ${VERSION}

springdoc:
  group-configs:
    - group: config-client
      packages-to-scan:
       - org.bougainvilleas.spring.configclient