/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bougainvilleas_base_jvm_runtime_NativeMethodTest */

#ifndef _Included_org_bougainvilleas_base_jvm_runtime_NativeMethodTest
#define _Included_org_bougainvilleas_base_jvm_runtime_NativeMethodTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_bougainvilleas_base_jvm_runtime_NativeMethodTest
 * Method:    sayHi
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_bougainvilleas_base_jvm_runtime_NativeMethodTest_sayHi
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_bougainvilleas_base_jvm_runtime_NativeMethodTest
 * Method:    Native1
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_bougainvilleas_base_jvm_runtime_NativeMethodTest_Native1
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_bougainvilleas_base_jvm_runtime_NativeMethodTest
 * Method:    Native2
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_bougainvilleas_base_jvm_runtime_NativeMethodTest_Native2
  (JNIEnv *, jclass);

/*
 * Class:     org_bougainvilleas_base_jvm_runtime_NativeMethodTest
 * Method:    Native3
 * Signature: (Ljava/lang/Object;)F
 */
JNIEXPORT jfloat JNICALL Java_org_bougainvilleas_base_jvm_runtime_NativeMethodTest_Native3
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_bougainvilleas_base_jvm_runtime_NativeMethodTest
 * Method:    Native4
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_org_bougainvilleas_base_jvm_runtime_NativeMethodTest_Native4
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
