mysql:
  ip: ${MYSQL_IP:192.168.1.131}
  port: ${MYSQL_PORT:3306}
  database: ${MYSQL_DB:security}
  user: ${MYSQL_USER:park}
  pwd: ${MYSQL_PWD:park123}

# eureka配置，
HOSTNAME: mi # 本服务实例域名
PORT: 20000 # 本服务实例端口
GZ_IP: 127.0.0.1 # eureka 注册中心ip
GZ_PORT: 8761 # eureka 注册中心端口
SZ_IP: 127.0.0.1 # eureka 注册中心ip
SZ_PORT: 8760 # eureka 注册中心端口
# 管理接口 配置
MPATH: /admin # management.endpoints.web.base-path
VERSION: 0.0.3 # 本服务版本号
APPDESC: 用户中心 # 本服务描述信息
# 日志
LOGLEV: INFO
# enc() 加密配置文件
KEY: bougainvillea

swagger:
  enable: true
  info:
    title: ${spring.application.name}
    description: ${APPDESC}
    version: ${VERSION}
springdoc:
  group-configs:
    - group: user-v1
      packages-to-scan:
        - org.bougainvillea.spring.user
        - org.bougainvillea.spring.user.v1
      paths-to-exclude: /stop