---
name: All In One
description: study records static sites
url: https://bougainvilleas.github.io/aio/
repository: https://github.com/bougainvilleas/aio
timezone: Asia/Shanghai
logo: "/assets/img/bougainvillea.png"
baseurl: /aio

relative_links:
  enabled: true

collections:
  docs:
    permalink: "/:path"
    output: true

defaults:
  - scope:
      path: _docs
      type: "docs"
    values:
      layout: content
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-relative-links

#theme: jekyll-theme-hacker
