---
name: All In One
description: study records static sites
url: https://bougainvilleas.github.io/aio/
repository: https://github.com/bougainvilleas/aio
timezone: Asia/Shanghai
logo: "/assets/img/bougainvillea.png"
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true

#defaults:
#  - scope:
#      path: _docs
#      type: "docs"
#    values:
#      layout: default
#  - scope:
#      path: _docs/jvm
#      type: "jvm"
#    values:
#      layout: default
#  - scope:
#      path: ""
#    values:
#      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

#theme: jekyll-theme-hacker
